apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brats-checkpoints
  namespace: gai-lina-group
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi 
