apiVersion: v1
kind: Pod
metadata:
  name: data-pod
spec:
  nodeSelector:
    #topology.kubernetes.io/region: us-west
    nautilus.io/linstor: "true"
  
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      
      env:
        - name: REPO_PATH
          value: /app/UNETR-BraTS-Synthesis
        - name: PYTHONPATH
          value: /app/UNETR-BraTS-Synthesis
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"
      
      command: ["/bin/bash", "-c"]
      args:
        - |
          sudo apt update && sudo apt install zip
          # pip install --upgrade synapseclient 
          #sudo apt-get update && sudo apt-get install -y p7zip-full wget git

          # run the below in kubectl exec -- bash s
          # synapse get syn51669979  
          # will prompt for token obtained at https://accounts.synapse.org/authenticated/personalaccesstokens

          tail -f /dev/null
      
      volumeMounts:
        - name: workspace
          mountPath: /app
        - name: data2
          mountPath: /data2
        - name: data3
          mountPath: /data3
        - name: brats-data-m
          mountPath: /brats-data-m
        - name: shm
          mountPath: /dev/shm
      resources:
        requests:
          memory: 24Gi      
          cpu: "12"     
        limits:
          memory: 32Gi
          cpu: "16"
  
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 50Gi
    - name: data2
      persistentVolumeClaim:
        claimName: brats2025-2
    - name: data3
      persistentVolumeClaim:
        claimName: brats2025-3
    - name: brats-data-m
      persistentVolumeClaim:
        claimName: brats-data-m
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  
  restartPolicy: Never